name: build

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    env:
      RELEASE_SERVICES_JSON: ${{ secrets.RELEASE_SERVICES_JSON }}
      RELEASE_SIGNING_GRADLE: ${{ secrets.SIGNING_GRADLE }}
      RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      FIREBASE_TOKEN:  ${{ secrets.FIREBASE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting Debug Files
        run: |
          mkdir -p app/src/release
          echo ${RELEASE_SERVICES_JSON} | base64 -d > app/src/release/google-services.json
          echo ${RELEASE_SIGNING_GRADLE} | base64 -d > dependencies/signing.gradle
          echo ${RELEASE_KEYSTORE} | base64 -d > dependencies/release.keystore

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew clean assembleRelease

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: App Distribution Upload
        run: |
          echo `git log -1` > dependencies/app-distribution-note.txt
          ./gradlew appDistributionUploadRelease
